//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverterApp.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BamToEur", ReplyAction="*")]
        float BamToEur(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BamToEur", ReplyAction="*")]
        System.Threading.Tasks.Task<float> BamToEurAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurToBam", ReplyAction="*")]
        float EurToBam(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurToBam", ReplyAction="*")]
        System.Threading.Tasks.Task<float> EurToBamAsync(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CurrencyConverterApp.ServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CurrencyConverterApp.ServiceReference.WebService1Soap>, CurrencyConverterApp.ServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float BamToEur(int num) {
            return base.Channel.BamToEur(num);
        }
        
        public System.Threading.Tasks.Task<float> BamToEurAsync(int num) {
            return base.Channel.BamToEurAsync(num);
        }
        
        public float EurToBam(int num) {
            return base.Channel.EurToBam(num);
        }
        
        public System.Threading.Tasks.Task<float> EurToBamAsync(int num) {
            return base.Channel.EurToBamAsync(num);
        }
    }
}
